#!/usr/bin/env python3
"""
build-node-index.py — GENERATE the node directory from frontmatter.

Every governance/memory node carries frontmatter (name, description, trigger,
tier). They're scattered across files, so finding "which node for task X" or
"where does Y live" means grepping the whole repo. This walks the nodes once and
emits ONE compact directory (memory/NODE-INDEX.md) — the scan layer for
navigation. Read the directory (cheap), open the one node on demand.

Generated, never hand-edited (status tables that are hand-kept rot). Re-run:
  python scripts/build-node-index.py          # writes memory/NODE-INDEX.md
  python scripts/build-node-index.py --check   # exit 1 if the index is stale/missing

This is the representation policy applied to navigation: compact index + render
(open the node) on demand. Not a substitute for graphify (which maps CODE);
this maps the GOVERNANCE/MEMORY nodes by their trigger.
"""
import os, sys, re

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import store_policy

REPO = os.path.abspath(os.environ.get("CLAUDE_PROJECT_DIR")
                       or os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "memory", "NODE-INDEX.md")

# Roots to scan. Root governance files + the memory tree.
ROOT_FILES = ["CLAUDE.md", "AGENTS.md", "GEMINI.md", "DESIGN.md", "goodmorning.md"]
SCAN_DIRS = ["memory"]
# ⛔ ONE OWNER SINCE 2026-09-22: `.store-policy.json`, read through scripts/store_policy.py.
# This list used to be a hand-maintained twin of node-health.py's SKIP, held together by a comment in
# the other file. Worse, the two wrote the SAME paths differently — os.path.join here, "memory/archive"
# there — so they were not even diffable, and only one of them was visible to the portability gate.
# A store with no policy file skips nothing, which for an index generator means it indexes more.
def SKIP():
    return store_policy.load(REPO).excluded_dirs

def parse_frontmatter(text):
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    if not m:
        return None
    fm, body = {}, m.group(1)
    for line in body.splitlines():
        mm = re.match(r"^(\w[\w-]*):\s*(.*)$", line)
        if mm:
            fm[mm.group(1)] = mm.group(2).strip()
    return fm

def is_router(path, text):
    head = text[:600].lower()
    return ("this file is a router" in head) or ("thin index" in head) or ("thin router" in head)

def collect():
    nodes = []
    files = [os.path.join(REPO, f) for f in ROOT_FILES if os.path.exists(os.path.join(REPO, f))]
    for d in SCAN_DIRS:
        for root, dirs, fns in os.walk(os.path.join(REPO, d)):
            rel = os.path.relpath(root, REPO).replace("\\", "/")
            if any(s.replace("\\", "/") in rel for s in SKIP()):
                dirs[:] = []
                continue
            for fn in fns:
                if fn.endswith(".md"):
                    files.append(os.path.join(root, fn))
    for fp in files:
        try:
            text = open(fp, encoding="utf-8").read()
        except Exception:
            continue
        rel = os.path.relpath(fp, REPO).replace("\\", "/")
        fm = parse_frontmatter(text)
        n_lines = text.count("\n") + 1
        if fm and fm.get("name"):
            nodes.append({"name": fm["name"], "path": rel, "lines": n_lines,
                          "tier": fm.get("tier", ""), "trigger": fm.get("trigger", ""),
                          "desc": fm.get("description", ""), "router": False})
        elif rel in ROOT_FILES or is_router(rel, text):
            # routers / always-on files have no frontmatter but ARE entry points
            nodes.append({"name": os.path.basename(rel), "path": rel, "lines": n_lines,
                          "tier": "router", "trigger": "", "desc": "(router / always-on entry)",
                          "router": True})
        elif rel.startswith("memory/wiki/"):
            # durable-knowledge docs: index even without frontmatter, using the
            # first heading as name + the italic _tagline_ as the description.
            h = re.search(r"^#\s+(.+)$", text, re.M)
            tag = re.search(r"^_([^_]{8,200})_", text, re.M)
            name = (h.group(1).strip() if h else os.path.basename(rel)[:-3])
            nodes.append({"name": name, "path": rel, "lines": n_lines, "tier": "wiki",
                          "trigger": "", "desc": (tag.group(1).strip() if tag else ""),
                          "router": False})
    return nodes

def group(rel):
    if "/" not in rel:
        return "· entry points (routers / always-on)"
    parts = rel.split("/")
    if parts[0] == "memory" and len(parts) > 2:
        return "memory/" + parts[1] + ("/" + parts[2] if parts[1] == "design" and parts[2] == "aris" else "")
    return "/".join(parts[:2])

def render(nodes):
    out = ["<!-- GENERATED by scripts/build-node-index.py — DO NOT HAND-EDIT. Re-run to refresh. -->",
           "# Node Directory (generated)", "",
           f"_The scan layer for navigation: {len(nodes)} nodes by trigger. Find the node here, then open it — don't grep. "
           "Routers/always-on first. For CODE questions use `graphify query`; this maps governance/memory nodes._", ""]
    groups = {}
    for n in nodes:
        groups.setdefault(group(n["path"]), []).append(n)
    # entry points first, then alpha
    def gkey(g): return (0, g) if g.startswith("·") else (1, g)
    for g in sorted(groups, key=gkey):
        items = sorted(groups[g], key=lambda x: x["path"])
        out.append(f"## {g}")
        out.append("| node | when to load | path | ln |")
        out.append("|---|---|---|---|")
        for n in items:
            trig = (n["trigger"] or n["desc"])[:90].replace("|", "\\|")
            out.append(f"| `{n['name']}` | {trig} | `{n['path']}` | {n['lines']} |")
        out.append("")
    return "\n".join(out) + "\n"

def main():
    nodes = collect()
    content = render(nodes)
    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            print("node-index MISSING — run: python scripts/build-node-index.py"); sys.exit(1)
        cur = open(OUT, encoding="utf-8").read()
        # compare ignoring the generated-comment line
        norm = lambda s: "\n".join(l for l in s.splitlines() if not l.startswith("<!--"))
        if norm(cur) != norm(content):
            print(f"node-index STALE — {len(nodes)} nodes now; re-run build-node-index.py"); sys.exit(1)
        print(f"node-index fresh ({len(nodes)} nodes)"); sys.exit(0)
    open(OUT, "w", encoding="utf-8").write(content)
    print(f"wrote {os.path.relpath(OUT, REPO)} — {len(nodes)} nodes")

if __name__ == "__main__":
    main()
