#!/usr/bin/env python3
"""
node-corrector.py — propose (and, gated, apply) fixes for the rot node-health flags.

The Corrector in the fleet roster (directory-agents-roadmap). Honors the non-negotiables: bounded,
gated, strictly-improves, Claude-or-human adopts. It does NOT free-edit the store — by default it only
PROPOSES, writing a compact board to the contract memory directory. `--apply` applies ONLY the
high-confidence, deterministic, reversible subset:

  BROKEN PATHS (the 259-rot):
    - unique basename match elsewhere in the repo  → CONFIDENT relocation (the file moved). --apply rewrites it.
    - zero matches (file truly gone)               → human decision (reported, never auto-touched).
    - multiple matches (ambiguous basename)        → human decision (reported, never auto-touched).
  DANGLING [[links]]:
    - closest resolvable node name (difflib)       → SUGGESTION only. Never auto-applied (too semantic).

Reuses node-health's scan (one source of truth — no scanner drift). Uses `git ls-files` as the basename
universe so it matches against tracked files only.

Usage:
  python3 scripts/node-corrector.py            # propose → writes the board, prints a summary
  python3 scripts/node-corrector.py --apply    # also apply the CONFIDENT relocations
  python3 scripts/node-corrector.py --limit 50
"""
import argparse, os, re, subprocess, sys, datetime, difflib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pathlib import Path
from store_contract import StoreContract, ContractError

contract = None
nh = None
REPO = None
BOARD = None


def tracked_basenames():
    result = subprocess.run(["git", "ls-files"], cwd=REPO, capture_output=True, text=True)
    if result.returncode:
        raise ContractError(f"corrector: cannot read tracked-file universe at {REPO}: {result.stderr.strip()}")
    out = result.stdout
    by_base = {}
    for rel in out.splitlines():
        by_base.setdefault(os.path.basename(rel), []).append(rel)
    return by_base


# never auto-edit these (always-on governance) and never relocate a live ref INTO a retired area
ROOT_GOVERNANCE = {"CLAUDE.md", "AGENTS.md", "GEMINI.md", "goodmorning.md", "RECOVERY.md", "DESIGN.md", "PIPELINE.md"}
RETIRED = ("_archive", "exports", ".space",
           # scratch/ is EPHEMERAL, not retired — and that is worse for auto-repair. It is WIPED at
           # 14 days (scripts/scratch-keeper.py MAX_AGE_DAYS=14), so "repairing" a broken link to
           # point INTO it manufactures a link guaranteed to break again, and to break silently,
           # after the evidence of what it once pointed at is gone. Observed 2026-07-19: two
           # handoffs had their crystal-probe paths auto-rewritten into
           # scratch/dead-weight-cut-2026-07-18/ (created 07-18, due to vanish ~08-01).
           # A dead link that ANNOUNCES itself beats a live link that expires unnoticed.
           "scratch/")


def looks_like_path(path):
    """A real repo path uses lowercase directory segments. An ALL-CAPS dir segment (e.g.
    'CLAUDE/AGENTS/GEMINI/...') is a shorthand ENUMERATION in prose, not a file path — don't 'fix' it."""
    dirs = path.split("/")[:-1]
    return all(d == d.lower() for d in dirs)


def classify_broken(broken, by_base):
    """confident = unique basename match that is SAFE to auto-apply; everything dubious → human buckets."""
    confident, gone, ambiguous, skipped = [], [], [], []
    for rel, path in broken:
        if not looks_like_path(path):
            skipped.append((rel, path, "looks like a prose enumeration, not a path"))
            continue
        base = os.path.basename(path)
        # candidate targets: same basename, not the path itself, NOT in a retired area
        matches = [m for m in by_base.get(base, []) if m != path and not any(s in m for s in RETIRED)]
        if len(matches) == 1:
            confident.append((rel, path, matches[0]))
        elif not matches:
            gone.append((rel, path))
        else:
            ambiguous.append((rel, path, matches))
    return confident, gone, ambiguous, skipped


def suggest_links(dangling, resolvable):
    out = []
    pool = sorted(resolvable)
    for rel, link in dangling:
        near = difflib.get_close_matches(link.lower(), pool, n=1, cutoff=0.7)
        out.append((rel, link, near[0] if near else None))
    return out


def write_board(confident, gone, ambiguous, skipped, link_suggest, applied):
    # IMPORTANT: do NOT write paths in backticks or targets in [[ ]] — that would make node-health
    # re-flag this very board. Render them plain so the board stays health-clean.
    L = ["# Corrector board — proposals (gated; Claude/human adopts)", "",
         "_Generated by `scripts/node-corrector.py`. Confident relocations are auto-applyable with `--apply`; "
         "everything else is a human decision. Paths/links are rendered plain on purpose (so this board doesn't "
         "itself trip node-health)._", ""]
    L.append(f"## Confident relocations — {'APPLIED' if applied else 'run --apply to fix'} ({len(confident)})")
    for rel, old, new in confident:
        L.append(f"- {rel}: {old}  →  {new}")
    L.append("")
    L.append(f"## Broken — file gone, human decision ({len(gone)})")
    for rel, old in gone:
        L.append(f"- {rel}: {old}  (no file with that name exists — update or delete the reference)")
    L.append("")
    L.append(f"## Ambiguous basename — human decision ({len(ambiguous)})")
    for rel, old, matches in ambiguous:
        L.append(f"- {rel}: {old}  →  one of: {', '.join(matches)}")
    L.append("")
    L.append(f"## Skipped — not a real path (prose enumeration etc.), left alone ({len(skipped)})")
    for rel, old, why in skipped:
        L.append(f"- {rel}: {old}  ({why})")
    L.append("")
    L.append(f"## Dangling links — suggestions only, never auto-applied ({len(link_suggest)})")
    for rel, link, near in link_suggest:
        L.append(f"- {rel}: [[{link}]] ".replace("[[", "«").replace("]]", "»") +
                 (f"→ did you mean: {near}" if near else "→ (no close node name)"))
    L.append("")
    open(BOARD, "w", encoding="utf-8").write("\n".join(L) + "\n")


def apply_confident(confident):
    """Rewrite each confident broken path to its relocated target, in-place, in the referencing file.
    Skips always-on governance files — those are a human decision, never an auto-edit."""
    by_file = {}
    for rel, old, new in confident:
        if rel in ROOT_GOVERNANCE:
            continue
        by_file.setdefault(rel, []).append((old, new))
    fixed = 0
    for rel, pairs in by_file.items():
        fp = os.path.join(REPO, rel)
        if not editable(fp):
            continue
        txt = open(fp, encoding="utf-8").read()
        new_txt = txt
        for old, new in pairs:
            # only rewrite the backtick-wrapped form node-health actually flags
            new_txt = new_txt.replace(f"`{old}`", f"`{new}`")
        if new_txt != txt:
            open(fp, "w", encoding="utf-8").write(new_txt)
            fixed += sum(1 for old, _ in pairs if f"`{old}`" in txt)
    return fixed


def editable(path):
    # A directory allowlist is not evidence of authorship. --apply additionally
    # requires an explicit local-author file allowlist; imported/unknown text is
    # proposal-only. Imported metadata cannot be overridden by that allowlist.
    allowed = {str((contract.root / p).resolve()) for p in
               os.environ.get("CORRECTOR_OWN_FILES", "").split(os.pathsep) if p}
    p = Path(path)
    if p.is_symlink() or p not in contract.node_files() or str(p.resolve()) not in allowed:
        return False
    text = p.read_text(encoding="utf-8")
    fm = text.split("---", 2)[1] if text.startswith("---") and text.count("---") >= 2 else ""
    return not re.search(r"(?im)^\s*(?:imported|source|source_url|origin|provenance)\s*:", fm)


def main():
    p = argparse.ArgumentParser(description="Propose/apply fixes for node-health-flagged rot.")
    p.add_argument("--apply", action="store_true", help="apply the CONFIDENT relocations (gated)")
    p.add_argument("--limit", type=int, default=0, help="cap items per category (0 = no cap)")
    a = p.parse_args()
    global contract, nh, REPO, BOARD, RETIRED
    contract = StoreContract()
    BOARD = str(contract.output(contract.memory_dir, "corrector-inbox.md"))
    contract.require_nodes()
    nh = contract.health("corrector")
    REPO = str(contract.root)
    RETIRED += (str((contract.memory_dir / "archive").relative_to(contract.root)),)

    files = nh.node_files()
    resolvable = nh.build_resolvable(files)
    dangling, broken, _stale, _un = nh.scan(files, resolvable, datetime.date.today(), 120)
    by_base = tracked_basenames()
    confident, gone, ambiguous, skipped = classify_broken(broken, by_base)
    link_suggest = suggest_links(dangling, resolvable)

    if a.limit:
        confident, gone, ambiguous, skipped = (confident[:a.limit], gone[:a.limit],
                                               ambiguous[:a.limit], skipped[:a.limit])
        link_suggest = link_suggest[:a.limit]

    # confident set that is auto-applyable (governance files excluded from --apply)
    applyable = [c for c in confident if c[0] not in ROOT_GOVERNANCE and editable(os.path.join(REPO, c[0]))]
    applied = 0
    if a.apply and applyable:
        applied = apply_confident(confident)

    write_board(confident, gone, ambiguous, skipped, link_suggest, applied=a.apply)

    print("node-corrector:")
    print(f"  CONFIDENT relocations: {len(confident)} ({len(applyable)} auto-applyable, "
          f"{len(confident)-len(applyable)} protected/imported/unknown authorship → human)" +
          (f"  → APPLIED {applied}" if a.apply else "  (run --apply to fix the applyable ones)"))
    print(f"  broken, file gone:     {len(gone)}  (human)")
    print(f"  ambiguous basename:    {len(ambiguous)}  (human)")
    print(f"  skipped (non-path):    {len(skipped)}")
    print(f"  dangling-link hints:   {len(link_suggest)}  (suggestions only)")
    print(f"  board → {os.path.relpath(BOARD, REPO)}")
    if a.apply and applied:
        print("  Next: review the diff, run node-health to confirm, then commit.")


if __name__ == "__main__":
    try:
        main()
    except (ContractError, OSError) as error:
        print(f"node-corrector: {error}", file=sys.stderr)
        sys.exit(1)
